---

- name: Nexus Ping
  hosts: nxos2
  gather_facts: false

  vars:
    device:
        host: "{{ host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        transport: nxapi

  tasks:
    - name: Nexus Ping
      nxos_ping:
        provider: "{{ device }}"
        dest: 10.100.100.2
        count: 5
        vrf: default
      register: output

    - debug: msg="{{ output }}"
